#!/usr/bin/env python3
"""Generate the SEO head block, crawlable footer, and sitemap/robots for docs/.

``docs/`` is the yeaboi.ai website: hand-written flat HTML with no build step,
served straight off ``main`` by GitHub Pages (``docs/CNAME``). That works fine
for prose, and not at all for the dozen ``<meta>`` tags every page needs to be
indexable — 18 files x (canonical + 10 OG/Twitter tags + JSON-LD + an analytics
snippet) is precisely the thing that rots the moment someone adds page 19.

The evidence it already rots: the same four asset references carry a
hand-bumped ``?v=`` on every page, 72 strings that have to agree and that
nothing checks. So this script owns the cache-bust too — one constant, one
command, and ``tests/unit/test_site_seo.py`` fails if the committed HTML is
stale.

**What it does not own: the words.** Each page's ``<title>`` and
``<meta name="description">`` are hand-written and good, and they live where an
author would naturally edit them. This script *parses* them out and reuses them
in the OG/Twitter/JSON-LD tags. A registry of marketing copy in a Python dict
would be worse than the problem it solved.

Three non-obvious constraints, each learned the hard way:

1. **Nothing may depend on the clock, the git history, or the package version.**
   ``--check`` has to produce identical bytes in CI, and CI checks out at
   ``fetch-depth: 1``. So: no ``<lastmod>`` in the sitemap (a git-derived date
   disagrees with a shallow clone) and no ``softwareVersion`` in the JSON-LD
   (``auto-version.yml`` pushes a version bump to PR branches and regenerates
   nothing, so every such PR would go stale).
2. **Output must be LF, trailing-whitespace-free, with exactly one final
   newline.** ``.pre-commit-config.yaml`` runs ``trailing-whitespace`` and
   ``end-of-file-fixer`` over ``docs/``; if the generator disagrees with the
   hooks they rewrite each other forever and ``--check`` never converges.
3. **``NAV_GROUPS`` in site.js is read, never written.** It is the single source
   of truth for the docs tree and it drives the crawlable footer here. Writing
   it back would put a generated JS literal in a 1630-line hand-tuned file with
   no Node in the Python CI lane to syntax-check the result — one malformed
   literal would break every script on the site.

Usage::

    uv run python scripts/gen_site_seo.py          # write
    uv run python scripts/gen_site_seo.py --check  # fail if stale (CI + pytest)
"""

from __future__ import annotations

import argparse
import html
import json
import logging
import re
import sys
from enum import StrEnum
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
SITE_JS = DOCS / "assets" / "site.js"
SITE = "https://yeaboi.ai"

logger = logging.getLogger(__name__)

# Bump when anything under docs/assets/ or docs/docs/assets/ changes. Rewritten
# into every ?v= on every page, so this is the only place it is ever edited.
ASSET_VERSION = 136

# A GA4 measurement ID is a public identifier — it ships in the page source of
# every GA site on the web — so it belongs in the repo, not in a secret. While
# it is the placeholder the GA block is omitted entirely rather than emitted
# with a dead ID: a placeholder that reaches production is a silent failure,
# and "no analytics yet" is an honest state that keeps the test suite green.
GA_PLACEHOLDER = "G-XXXXXXXXXX"
GA_MEASUREMENT_ID = "G-K9HLPT5ZMP"

# Same pattern: paste the token from Search Console and the tag appears.
GSC_VERIFICATION = "ttjn2iHRRMXJajyb-4HgKW_9it0K0XLCnDvgxf5DQQY"

OG_CARD = "/assets/og-card.png"
OG_CARD_ALT = "yeaboi — best friend to engineers and agents"
OG_CARD_W, OG_CARD_H = 1200, 630

HEAD_BEGIN = "<!-- SEO:BEGIN -->"
HEAD_END = "<!-- SEO:END -->"
FOOT_BEGIN = "<!-- SEO:FOOT:BEGIN -->"
FOOT_END = "<!-- SEO:FOOT:END -->"

_GENERATED_NOTE = (
    "generated by scripts/gen_site_seo.py — do not edit by hand; run `make site-seo` and commit the result"
)


class Kind(StrEnum):
    """How a page is treated for schema and indexing purposes."""

    LANDING = "landing"  # docs/index.html — the marketing page at /
    HUB = "hub"  # a section index that lists its children
    ARTICLE = "article"  # a leaf documentation page
    ERROR = "error"  # 404.html — noindex, no canonical, not in the sitemap


# Two-way checked against the actual files on disk by test_site_seo.py, so a
# new page without an entry here fails the suite with the exact edit named.
KINDS: dict[str, Kind] = {
    "index.html": Kind.LANDING,
    "404.html": Kind.ERROR,
    "docs/index.html": Kind.HUB,
    "docs/modes/index.html": Kind.HUB,
    "docs/agents/index.html": Kind.HUB,
    "docs/getting-started.html": Kind.ARTICLE,
    "docs/cli-reference.html": Kind.ARTICLE,
    "docs/integrations-exports.html": Kind.ARTICLE,
    "docs/session-management.html": Kind.ARTICLE,
    "docs/tools.html": Kind.ARTICLE,
    "docs/architecture.html": Kind.ARTICLE,
    "docs/scrum-standards.html": Kind.ARTICLE,
    "docs/development.html": Kind.ARTICLE,
    "docs/modes/planning.html": Kind.ARTICLE,
    "docs/modes/standup.html": Kind.ARTICLE,
    "docs/modes/retro.html": Kind.ARTICLE,
    "docs/modes/poker.html": Kind.ARTICLE,
    "docs/modes/performance.html": Kind.ARTICLE,
    "docs/modes/reporting.html": Kind.ARTICLE,
    "docs/modes/team-analysis.html": Kind.ARTICLE,
    "docs/agents/usage.html": Kind.ARTICLE,
    "docs/agents/advisor.html": Kind.ARTICLE,
    "docs/agents/standup.html": Kind.ARTICLE,
    "docs/agents/security.html": Kind.ARTICLE,
}


# ---------------------------------------------------------------------------
# paths and parsing
# ---------------------------------------------------------------------------


def rel_of(path: Path) -> str:
    """Repo-relative posix key under ``docs/`` — the key used by KINDS."""
    return path.relative_to(DOCS).as_posix()


def url_for(path: Path) -> str:
    """Site-absolute URL for a repo path, applying the Pages strip rule.

    GitHub Pages serves ``docs/`` AS the domain root, so exactly one directory
    level disappears: ``docs/docs/modes/retro.html`` is served at
    ``/docs/modes/retro.html``. Only the site root index collapses to ``/``.

    Note ``docs/docs/index.html`` maps to ``/docs/index.html``, NOT ``/docs/``,
    even though both URLs resolve. Every path in ``NAV_GROUPS``, the hardcoded
    ``navigateTo("/docs/index.html", true)`` in ``buildRail``, and
    ``setDocsCurrent``'s string-equality check all use the explicit filename —
    canonicalising to the prettier form would disagree with every internal link
    on the site and break the current-page highlight. The canonical tag still
    consolidates the duplicate, which is the part that matters to a crawler.
    """
    rel = rel_of(path)
    return "/" if rel == "index.html" else "/" + rel


_TITLE_RE = re.compile(r"^<title>(.*)</title>\s*$", re.MULTILINE)
_DESC_RE = re.compile(r'^<meta name="description" content="(.*)" />\s*$', re.MULTILINE)
_H1_RE = re.compile(r"<h1[^>]*>(.*?)</h1>", re.DOTALL)
_TAGS_RE = re.compile(r"<[^>]+>")


def _text(raw: str) -> str:
    """Markup fragment to canonical plain text (entities resolved, tags gone)."""
    return html.unescape(_TAGS_RE.sub("", raw)).strip()


def page_copy(text: str, path: Path) -> tuple[str, str, str]:
    """Extract (title, description, h1) as canonical plain text.

    Raises rather than guessing: a page whose head does not match the shape
    every other page uses is a bug to fix, not something to paper over with a
    default that would then be silently wrong in a social card.
    """
    for name, pattern in (("<title>", _TITLE_RE), ("description", _DESC_RE), ("<h1>", _H1_RE)):
        if not pattern.search(text):
            msg = f"{rel_of(path)}: no single-line {name} found — cannot generate SEO tags"
            raise SystemExit(msg)
    title = _text(_TITLE_RE.search(text).group(1))
    desc = _text(_DESC_RE.search(text).group(1))
    h1 = _text(_H1_RE.search(text).group(1))
    return title, desc, h1


# ---------------------------------------------------------------------------
# NAV_GROUPS — read out of site.js, the single source of truth
# ---------------------------------------------------------------------------

_NAV_KEY_RE = re.compile(r"([{,]\s*)(label|entries|title|path|children)(\s*:)")


def parse_nav_groups(js: str) -> list[dict]:
    """Read the ``NAV_GROUPS`` array literal out of site.js as Python data.

    The literal is a strict JSON subset apart from unquoted keys and trailing
    commas, both of which are mechanical to fix. Sliced by brace depth rather
    than by regex so a nested ``children`` array can't terminate the match
    early. A malformed literal raises here at generation time — loud and
    immediate, which is the only acceptable failure mode for a parse like this.
    """
    start = js.index("var NAV_GROUPS = [") + js[js.index("var NAV_GROUPS = [") :].index("[")
    depth = 0
    for i, ch in enumerate(js[start:], start):
        if ch == "[":
            depth += 1
        elif ch == "]":
            depth -= 1
            if depth == 0:
                literal = js[start : i + 1]
                break
    else:  # pragma: no cover - unbalanced brackets in site.js
        msg = "NAV_GROUPS in site.js has unbalanced brackets"
        raise SystemExit(msg)

    quoted = _NAV_KEY_RE.sub(r'\1"\2"\3', literal)
    no_trailing = re.sub(r",(\s*[\]}])", r"\1", quoted)
    return json.loads(no_trailing)


def nav_lookup(groups: list[dict]) -> dict[str, tuple[str, str | None, str]]:
    """Map each nav path to ``(group_label, parent_path, title)``.

    ``parent_path`` is set only for pages nested under another entry's
    ``children`` — that is what produces the four-level breadcrumb for a mode
    page versus the three-level one for everything else.
    """
    out: dict[str, tuple[str, str | None, str]] = {}
    for group in groups:
        for entry in group["entries"]:
            out[entry["path"]] = (group["label"], None, entry["title"])
            for child in entry.get("children", ()):
                out[child["path"]] = (group["label"], entry["path"], child["title"])
    return out


# ---------------------------------------------------------------------------
# escaping
# ---------------------------------------------------------------------------


def attr(value: str) -> str:
    """Escape for an HTML attribute value."""
    return html.escape(value, quote=True)


def json_ld(payload: dict) -> str:
    """Serialise JSON-LD so it cannot break out of its <script> element.

    Same rule as ``src/yeaboi/web/assets.py:json_island``: ``</script>`` inside
    a JSON string would end the element, so the three characters that could
    start a tag are escaped as JSON unicode escapes (still valid JSON, parses
    to the same string). U+2028/9 are legal in JSON but not in JS string
    literals, and break older parsers.
    """
    raw = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    for bad, good in (("<", "\\u003c"), (">", "\\u003e"), ("&", "\\u0026"), (" ", "\\u2028"), (" ", "\\u2029")):
        raw = raw.replace(bad, good)
    return raw


# ---------------------------------------------------------------------------
# JSON-LD graphs
# ---------------------------------------------------------------------------

_ORG_ID = f"{SITE}/#organization"
_SITE_ID = f"{SITE}/#website"
_SOFTWARE_ID = f"{SITE}/#software"

# Kept in sync with pyproject.toml [project.urls] by test_site_seo.py.
REPO_URL = "https://github.com/dinho149/yeaboi.ai"
PYPI_URL = "https://pypi.org/project/yeaboi/"


def _organization() -> dict:
    return {
        "@type": "Organization",
        "@id": _ORG_ID,
        "name": "yeaboi",
        "alternateName": "yeaboi.ai",
        "url": f"{SITE}/",
        "logo": {
            "@type": "ImageObject",
            "url": f"{SITE}/assets/duck-base.png",
            "width": 480,
            "height": 509,
        },
        "sameAs": [REPO_URL, PYPI_URL],
    }


def _website(description: str) -> dict:
    return {
        "@type": "WebSite",
        "@id": _SITE_ID,
        "url": f"{SITE}/",
        "name": "yeaboi",
        "description": description,
        "publisher": {"@id": _ORG_ID},
        "inLanguage": "en",
    }


def _software_stub() -> dict:
    """Compact SoftwareApplication for use as ``about`` on docs pages.

    Repeated rather than referenced by bare ``@id``: Google resolves ``@id``
    only within the same JSON-LD block, so pointing at a node that exists only
    on the landing page would validate as an unresolved stub.
    """
    return {
        "@type": "SoftwareApplication",
        "@id": _SOFTWARE_ID,
        "name": "yeaboi",
        "applicationCategory": "DeveloperApplication",
        "operatingSystem": "macOS, Linux, Windows",
    }


def _software_full(description: str) -> dict:
    return {
        **_software_stub(),
        "url": f"{SITE}/",
        "description": description,
        "applicationSubCategory": "Project Management",
        "runtimePlatform": "Python 3.11+",
        "programmingLanguage": "Python",
        "codeRepository": REPO_URL,
        "downloadUrl": PYPI_URL,
        "installUrl": PYPI_URL,
        "license": "https://opensource.org/licenses/MIT",
        "isAccessibleForFree": True,
        "publisher": {"@id": _ORG_ID},
        "offers": {
            "@type": "Offer",
            "price": "0",
            "priceCurrency": "USD",
            "availability": "https://schema.org/InStock",
            "category": "Free, open source (MIT)",
        },
        "featureList": [
            "Planning — decompose a project into epics, stories, tasks and a sprint plan",
            "Daily Standup — detect shipped work, score sprint progress, deliver on a schedule",
            "Retro — a LAN retrospective board the whole team joins from any browser",
            "Planning Poker — live voting in the browser with points synced back to the board",
            "Performance — 1:1 prep, write-ups and six-month reviews from real delivery history",
            "Reporting — stakeholder summaries and a slide deck from delivered work",
            "Team Analysis — a reusable delivery profile that calibrates planning to real velocity",
            "Agent Usage — what your AI coding agents cost: tokens, cache, per-model and per-project spend",
            "Agent Advisor — the recoverable share of that spend: re-read waste, cache health, prefix churn",
            "Agent Standup — a daily digest of what your agents did: sessions, commits, PRs, open threads",
            "Agent Security — audit agent permissions, MCP servers, secrets exposure and risky commands",
        ],
        "softwareHelp": {"@type": "CreativeWork", "url": f"{SITE}/docs/index.html"},
        "image": f"{SITE}{OG_CARD}",
        # Deliberately no softwareVersion — see the module docstring.
    }


def _breadcrumbs(url: str, h1: str, lookup: dict) -> dict:
    """Breadcrumb trail from the nav tree, current page last and without a URL.

    The final item carries a ``name`` but no ``item``, which is Google's stated
    guidance for the page you are already on.
    """
    trail: list[tuple[str, str | None]] = [("Home", f"{SITE}/")]
    group_label, parent, _title = lookup.get(url, ("", None, h1))
    if url != "/docs/index.html":
        trail.append(("Docs", f"{SITE}/docs/index.html"))
    if parent:
        trail.append((lookup[parent][2], f"{SITE}{parent}"))
    elif group_label == "Modes" and url != "/docs/modes/index.html":
        trail.append(("Modes", f"{SITE}/docs/modes/index.html"))
    trail.append((h1, None))

    items = []
    for position, (name, item) in enumerate(trail, start=1):
        node: dict = {"@type": "ListItem", "position": position, "name": name}
        if item:
            node["item"] = item
        items.append(node)
    return {"@type": "BreadcrumbList", "@id": f"{SITE}{url}#breadcrumb", "itemListElement": items}


def _collection_items(url: str, groups: list[dict]) -> list[dict]:
    """ItemList for a hub page: its children, or every other page for /docs/."""
    if url == "/docs/modes/index.html":
        entries = [
            child
            for group in groups
            for entry in group["entries"]
            if entry["path"] == url
            for child in entry.get("children", ())
        ]
    else:
        entries = [entry for group in groups for entry in group["entries"] if entry["path"] != url]
    return [
        {"@type": "ListItem", "position": i, "name": e["title"], "url": f"{SITE}{e['path']}"}
        for i, e in enumerate(entries, start=1)
    ]


def build_graph(kind: Kind, url: str, title: str, desc: str, h1: str, groups: list[dict]) -> dict | None:
    """The full JSON-LD ``@graph`` for a page, or None if it gets none."""
    if kind is Kind.ERROR:
        return None

    lookup = nav_lookup(groups)
    if kind is Kind.LANDING:
        nodes = [_organization(), _website(desc), _software_full(desc)]
    elif kind is Kind.HUB:
        nodes = [
            {
                "@type": "CollectionPage",
                "@id": f"{SITE}{url}#page",
                "url": f"{SITE}{url}",
                "name": title,
                "description": desc,
                "inLanguage": "en",
                "isPartOf": {"@type": "WebSite", "@id": _SITE_ID, "url": f"{SITE}/", "name": "yeaboi"},
                "about": _software_stub(),
                "mainEntity": {
                    "@type": "ItemList",
                    "itemListOrder": "https://schema.org/ItemListOrderAscending",
                    "itemListElement": _collection_items(url, groups),
                },
            },
            _breadcrumbs(url, h1, lookup),
        ]
    else:
        nodes = [
            {
                "@type": "TechArticle",
                "@id": f"{SITE}{url}#article",
                "url": f"{SITE}{url}",
                "headline": h1,
                "name": title,
                "description": desc,
                "articleSection": lookup.get(url, ("", None, ""))[0],
                "inLanguage": "en",
                "image": f"{SITE}{OG_CARD}",
                "license": "https://opensource.org/licenses/MIT",
                "publisher": _organization(),
                "about": _software_stub(),
                "isPartOf": {"@type": "WebSite", "@id": _SITE_ID, "url": f"{SITE}/", "name": "yeaboi"},
                "mainEntityOfPage": {"@type": "WebPage", "@id": f"{SITE}{url}"},
            },
            _breadcrumbs(url, h1, lookup),
        ]
    return {"@context": "https://schema.org", "@graph": nodes}


# ---------------------------------------------------------------------------
# the generated blocks
# ---------------------------------------------------------------------------


def _ga_lines() -> list[str]:
    """The GA4 snippet, or nothing at all while the ID is a placeholder.

    Lives in ``<head>`` and not the body because ``navigateTo`` swaps
    ``#page-content`` via ``outerHTML``, and a script inserted that way never
    executes — a body snippet would run on hard loads only.

    Consent Mode v2 defaults to denied and ``client_storage:'none'`` means no
    cookie is ever written, so no consent banner is required. The trade is that
    GA4 reports cookieless pings: user and session counts become modelled
    rather than exact, which is the right price for a docs site whose question
    is "which pages get read".
    """
    if GA_MEASUREMENT_ID == GA_PLACEHOLDER or not GA_MEASUREMENT_ID:
        return [
            "<!-- Google Analytics 4: not configured yet. Set GA_MEASUREMENT_ID in",
            "     scripts/gen_site_seo.py and re-run `make site-seo`. Emitting nothing",
            "     rather than a placeholder ID keeps a dead tag off production. -->",
        ]
    gid = attr(GA_MEASUREMENT_ID)
    return [
        f"<!-- Google Analytics 4 ({gid}). In <head> because navigateTo() swaps",
        "     #page-content with outerHTML, so a body script would never execute after a",
        "     client-side nav. Cookieless (client_storage:'none'), so no consent banner is",
        "     required. NOTE: 'Page changes based on browser history events' must be OFF in",
        "     the GA4 stream, or the explicit page_view in site.js double-counts. -->",
        f'<script async src="https://www.googletagmanager.com/gtag/js?id={gid}"></script>',
        "<script>",
        "window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}",
        "gtag('consent','default',{ad_storage:'denied',ad_user_data:'denied',"
        "ad_personalization:'denied',analytics_storage:'denied'});",
        "gtag('js',new Date());",
        f"gtag('config','{gid}',{{client_storage:'none',ads_data_redaction:true}});",
        "</script>",
    ]


def head_block(kind: Kind, url: str, title: str, desc: str, h1: str, groups: list[dict]) -> str:
    """The managed ``<head>`` block for one page."""
    lines = [HEAD_BEGIN, f"<!-- {_GENERATED_NOTE} -->"]

    if kind is Kind.ERROR:
        # noindex so a 404 never enters the index, follow so its links still
        # pass a lost crawler on to real pages.
        lines.append('<meta name="robots" content="noindex, follow" />')
    else:
        lines += [
            f'<link rel="canonical" href="{SITE}{url}" />',
            '<meta name="robots" content="index, follow, max-image-preview:large, '
            'max-snippet:-1, max-video-preview:-1" />',
        ]

    if GSC_VERIFICATION:
        lines.append(f'<meta name="google-site-verification" content="{attr(GSC_VERIFICATION)}" />')

    og_type = "article" if kind is Kind.ARTICLE else "website"
    lines += [
        '<meta property="og:site_name" content="yeaboi" />',
        '<meta property="og:locale" content="en_US" />',
        f'<meta property="og:type" content="{og_type}" />',
        f'<meta property="og:title" content="{attr(title)}" />',
        f'<meta property="og:description" content="{attr(desc)}" />',
    ]
    if kind is not Kind.ERROR:
        lines.append(f'<meta property="og:url" content="{SITE}{url}" />')
    lines += [
        f'<meta property="og:image" content="{SITE}{OG_CARD}" />',
        f'<meta property="og:image:secure_url" content="{SITE}{OG_CARD}" />',
        '<meta property="og:image:type" content="image/png" />',
        f'<meta property="og:image:width" content="{OG_CARD_W}" />',
        f'<meta property="og:image:height" content="{OG_CARD_H}" />',
        f'<meta property="og:image:alt" content="{attr(OG_CARD_ALT)}" />',
        '<meta name="twitter:card" content="summary_large_image" />',
        f'<meta name="twitter:title" content="{attr(title)}" />',
        f'<meta name="twitter:description" content="{attr(desc)}" />',
        f'<meta name="twitter:image" content="{SITE}{OG_CARD}" />',
        f'<meta name="twitter:image:alt" content="{attr(OG_CARD_ALT)}" />',
    ]

    graph = build_graph(kind, url, title, desc, h1, groups)
    if graph:
        lines.append(f'<script type="application/ld+json">{json_ld(graph)}</script>')

    lines += _ga_lines()
    lines.append(HEAD_END)
    return "\n".join(lines)


def footer_block(url: str, groups: list[dict]) -> str:
    """A static, visible nav footer — the fix for zero crawlable docs links.

    Before this, a crawler fetching any docs page saw no link to any sibling:
    the rail dropdown is built by JS into ``.rail-menu-inner`` and
    ``.rail-menu`` is ``visibility:hidden`` until ``.expanded``, while
    ``<aside id="docs-sidebar">`` is ``display:none`` and nothing in site.js
    ever writes to it. 15 leaf pages were reachable only from two hubs.

    Emitted after ``</article>`` rather than inside it, because
    ``_buildDocsIndex()`` indexes ``.docs-content article`` for the client-side
    search — 17 link titles per page would swamp every query. And never with
    ``data-reveal``, which starts at ``opacity:0``: a crawlable nav must not
    depend on JS running.
    """
    out = [
        FOOT_BEGIN,
        f"<!-- {_GENERATED_NOTE} -->",
        '<footer class="docs-foot">',
        '  <nav class="docs-foot-cols" aria-label="Documentation">',
    ]
    for group in groups:
        out += [
            '    <div class="nav-group">',
            f'      <p class="nav-group-label">{attr(group["label"])}</p>',
            "      <ul>",
        ]
        for entry in group["entries"]:
            for path, title in [(entry["path"], entry["title"])] + [
                (c["path"], c["title"]) for c in entry.get("children", ())
            ]:
                cur = ' aria-current="page"' if path == url else ""
                out.append(f'        <li><a href="{path}"{cur}>{attr(title)}</a></li>')
        out += ["      </ul>", "    </div>"]
    out += [
        "  </nav>",
        '  <div class="docs-foot-meta">',
        '    <span><a href="/">yeaboi</a> — best friend to engineers and agents</span>',
        "    <span>MIT licensed</span>",
        f'    <a href="{REPO_URL}" rel="noopener">GitHub ↗</a>',
        f'    <a href="{PYPI_URL}" rel="noopener">PyPI ↗</a>',
        "  </div>",
        "</footer>",
        FOOT_END,
    ]
    return "\n".join(out)


# ---------------------------------------------------------------------------
# rewriting
# ---------------------------------------------------------------------------

# Anchored on full lines and on these three prefixes only. `description`,
# `theme-color`, `color-scheme` and `viewport` are load-bearing and must
# survive — a greedier pattern eating one of those is the worst realistic
# outcome of this whole change.
_STRAY_RE = re.compile(
    r'^[ \t]*<(?:meta property="og:|meta name="twitter:|link rel="canonical").*?>[ \t]*\n',
    re.MULTILINE,
)
_ASSET_V_RE = re.compile(r'((?:href|src)="/(?:docs/)?assets/[^"?]+\?v=)\d+(")')


def _splice(text: str, begin: str, end: str, block: str, anchor: str, *, after: bool) -> str:
    """Replace a sentinel block, or insert it next to ``anchor`` on first run."""
    if begin in text:
        pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
        return pattern.sub(lambda _: block, text, count=1)
    if anchor not in text:
        msg = f"anchor {anchor!r} not found — cannot insert generated block"
        raise SystemExit(msg)
    if after:
        return text.replace(anchor, anchor + "\n" + block, 1)
    return text.replace(anchor, block + "\n" + anchor, 1)


def render(path: Path, groups: list[dict]) -> str:
    """The full desired contents of one HTML page."""
    text = path.read_text(encoding="utf-8")
    kind = KINDS[rel_of(path)]
    url = url_for(path)
    title, desc, h1 = page_copy(text, path)

    # Scrub hand-written og/twitter/canonical tags that the block now owns,
    # but only outside it, or re-running would eat its own output.
    if HEAD_BEGIN in text:
        head, sep, tail = text.partition(HEAD_BEGIN)
        body, sep2, rest = tail.partition(HEAD_END)
        text = _STRAY_RE.sub("", head) + sep + body + sep2 + _STRAY_RE.sub("", rest)
    else:
        text = _STRAY_RE.sub("", text)

    desc_line = _DESC_RE.search(text).group(0).rstrip("\n")
    text = _splice(text, HEAD_BEGIN, HEAD_END, head_block(kind, url, title, desc, h1, groups), desc_line, after=True)

    if kind is not Kind.LANDING and "</article>" in text:
        text = _splice(text, FOOT_BEGIN, FOOT_END, footer_block(url, groups), "</article>", after=True)

    text = _ASSET_V_RE.sub(rf"\g<1>{ASSET_VERSION}\g<2>", text)

    # LF, no trailing whitespace, exactly one final newline — or pre-commit's
    # hooks and this script rewrite each other forever.
    lines = [ln.rstrip() for ln in text.replace("\r\n", "\n").split("\n")]
    return "\n".join(lines).rstrip("\n") + "\n"


def render_sitemap(paths: list[Path]) -> str:
    """A <loc>-only sitemap. No lastmod/changefreq/priority — see the docstring."""
    urls = [url_for(p) for p in paths if KINDS[rel_of(p)] is not Kind.ERROR]
    body = "\n".join(f"  <url><loc>{SITE}{u}</loc></url>" for u in sorted(urls))
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        f"<!-- {_GENERATED_NOTE} -->\n"
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        f"{body}\n"
        "</urlset>\n"
    )


def render_robots() -> str:
    """robots.txt. No AI-crawler blocks: for an MIT dev tool, being quotable by
    assistants is distribution, not leakage — and that is a deliberate call.
    """
    return (
        f"# {_GENERATED_NOTE}\n"
        "User-agent: *\n"
        "Allow: /\n"
        "\n"
        "# Internal design docs, published by accident and now moved out of docs/.\n"
        "# Kept here for the window in which the old URLs are still cached.\n"
        "Disallow: /superpowers/\n"
        "# Orphan PDF carrying the superseded brand name; nothing links to it.\n"
        "Disallow: /ScrumTeamTraining.pdf\n"
        "\n"
        f"Sitemap: {SITE}/sitemap.xml\n"
    )


def pages() -> list[Path]:
    return sorted(DOCS.rglob("*.html"))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if any generated output is stale")
    args = parser.parse_args(argv)
    logging.basicConfig(level=logging.INFO, format="%(message)s")

    groups = parse_nav_groups(SITE_JS.read_text(encoding="utf-8"))
    found = {rel_of(p) for p in pages()}
    if missing := found - set(KINDS):
        msg = f"pages with no KINDS entry: {sorted(missing)} — add them to KINDS in {Path(__file__).name}"
        raise SystemExit(msg)

    wanted: dict[Path, str] = {p: render(p, groups) for p in pages()}
    wanted[DOCS / "sitemap.xml"] = render_sitemap(pages())
    wanted[DOCS / "robots.txt"] = render_robots()

    stale = [p for p, text in wanted.items() if not p.exists() or p.read_text(encoding="utf-8") != text]
    if args.check:
        if stale:
            names = "\n  ".join(str(p.relative_to(ROOT)) for p in stale)
            logger.error("stale generated site output:\n  %s\n\nrun: make site-seo", names)
            return 1
        logger.info("✓ docs/ SEO output is up to date (%d pages)", len(pages()))
        return 0

    for path, text in wanted.items():
        if path in stale:
            path.write_text(text, encoding="utf-8")
    logger.info("✓ wrote %d file(s) across %d pages", len(stale), len(pages()))
    return 0


if __name__ == "__main__":
    sys.exit(main())
